# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Which laptop should I buy?
tagline:          'Welchen Laptop soll ich kaufen?'
description:      'Eine laufend aktualisierte Liste an Laptops, und ein paar einfache Tipps zur Benutzung obendrauf. ;-)'
url:              https://whichlaptopshouldibuy.github.io
baseurl:          /

author:
  name:           'Linus Heimböck'

paginate:         1

# Custom vars
version:          2.1.0

#Plugins
plugins:
   - jekyll-paginate
